name: Fly Deploy

on:
  push:
    branches: [main]
    paths: [mail_api/**]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install flyctl
        run: curl -L https://fly.io/install.sh | sh && echo "$HOME/.fly/bin" >> $GITHUB_PATH
      - run: fly deploy --remote-only
        working-directory: mail_api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
